
// Generated by .hoplite/rig/render_ground_truth.py with the exact template
// strings extracted from the verified GGUF packages plus jinja2 ground-truth
// renders. Reconstructed templates (gated models) are labeled as such.

#include "chat_framing.h"

#include <cstdio>
#include <string>
#include <string_view>

using Laplace::ChatFraming;
using Laplace::compile_chat_framing;

namespace {

int g_failures = 0;

void check(bool condition, const char* detail) {
    if (!condition) {
        std::fprintf(stderr, "FAIL: %s\n", detail);
        ++g_failures;
    }
}

#define CHECK(cond) check((cond), #cond)
#define CHECK_MSG(cond, msg) check((cond), (msg))

void run_real_templates() {
    {
        const std::string_view template_text = R"TPL({% for message in messages %}{% if loop.first and messages[0]['role'] != 'system' %}{{ '<|im_start|>system
You are a helpful AI assistant named SmolLM, trained by Hugging Face<|im_end|>
' }}{% endif %}{{'<|im_start|>' + message['role'] + '
' + message['content'] + '<|im_end|>' + '
'}}{% endfor %}{% if add_generation_prompt %}{{ '<|im_start|>assistant
' }}{% endif %})TPL";
        const ChatFraming framing = compile_chat_framing(template_text);
        CHECK(framing.matched);
        if (framing.matched) {
            const std::string rendered = framing.system_prefix + framing.user_open +
                "Hello" + framing.turn_close + framing.generation_open;
            // Ground truth: jinja2 rendering of the same template with
            // messages=[{"role":"user","content":"Hello"}] and
            // add_generation_prompt=true.
            const std::string expected = R"TPL(<|im_start|>system
You are a helpful AI assistant named SmolLM, trained by Hugging Face<|im_end|>
<|im_start|>user
Hello<|im_end|>
<|im_start|>assistant
)TPL";
            CHECK_MSG(rendered == expected, "smollm2: facts render mismatch");
            CHECK(framing.user_open.find("user") != std::string::npos);
            CHECK(framing.assistant_open.find("assistant") != std::string::npos);
            CHECK(!framing.turn_close.empty());
            CHECK(!framing.generation_open.empty());
        }
    }
    {
        const std::string_view template_text = R"TPL({%- if tools %}
    {{- '<|im_start|>system\n' }}
    {%- if messages[0]['role'] == 'system' %}
        {{- messages[0]['content'] }}
    {%- else %}
        {{- 'You are Qwen, created by Alibaba Cloud. You are a helpful assistant.' }}
    {%- endif %}
    {{- "\n\n# Tools\n\nYou may call one or more functions to assist with the user query.\n\nYou are provided with function signatures within <tools></tools> XML tags:\n<tools>" }}
    {%- for tool in tools %}
        {{- "\n" }}
        {{- tool | tojson }}
    {%- endfor %}
    {{- "\n</tools>\n\nFor each function call, return a json object with function name and arguments within <tool_call></tool_call> XML tags:\n<tool_call>\n{{\"name\": <function-name>, \"arguments\": <args-json-object>}}\n</tool_call><|im_end|>\n" }}
{%- else %}
    {%- if messages[0]['role'] == 'system' %}
        {{- '<|im_start|>system\n' + messages[0]['content'] + '<|im_end|>\n' }}
    {%- else %}
        {{- '<|im_start|>system\nYou are Qwen, created by Alibaba Cloud. You are a helpful assistant.<|im_end|>\n' }}
    {%- endif %}
{%- endif %}
{%- for message in messages %}
    {%- if (message.role == "user") or (message.role == "system" and not loop.first) or (message.role == "assistant" and not message.tool_calls) %}
        {{- '<|im_start|>' + message.role + '\n' + message.content + '<|im_end|>' + '\n' }}
    {%- elif message.role == "assistant" %}
        {{- '<|im_start|>' + message.role }}
        {%- if message.content %}
            {{- '\n' + message.content }}
        {%- endif %}
        {%- for tool_call in message.tool_calls %}
            {%- if tool_call.function is defined %}
                {%- set tool_call = tool_call.function %}
            {%- endif %}
            {{- '\n<tool_call>\n{"name": "' }}
            {{- tool_call.name }}
            {{- '", "arguments": ' }}
            {{- tool_call.arguments | tojson }}
            {{- '}\n</tool_call>' }}
        {%- endfor %}
        {{- '<|im_end|>\n' }}
    {%- elif message.role == "tool" %}
        {%- if (loop.index0 == 0) or (messages[loop.index0 - 1].role != "tool") %}
            {{- '<|im_start|>user' }}
        {%- endif %}
        {{- '\n<tool_response>\n' }}
        {{- message.content }}
        {{- '\n</tool_response>' }}
        {%- if loop.last or (messages[loop.index0 + 1].role != "tool") %}
            {{- '<|im_end|>\n' }}
        {%- endif %}
    {%- endif %}
{%- endfor %}
{%- if add_generation_prompt %}
    {{- '<|im_start|>assistant\n' }}
{%- endif %}
)TPL";
        const ChatFraming framing = compile_chat_framing(template_text);
        CHECK(framing.matched);
        if (framing.matched) {
            const std::string rendered = framing.system_prefix + framing.user_open +
                "Hello" + framing.turn_close + framing.generation_open;
            // Ground truth: jinja2 rendering of the same template with
            // messages=[{"role":"user","content":"Hello"}] and
            // add_generation_prompt=true.
            const std::string expected = R"TPL(<|im_start|>system
You are Qwen, created by Alibaba Cloud. You are a helpful assistant.<|im_end|>
<|im_start|>user
Hello<|im_end|>
<|im_start|>assistant
)TPL";
            CHECK_MSG(rendered == expected, "qwen: facts render mismatch");
            CHECK(framing.user_open.find("user") != std::string::npos);
            CHECK(framing.assistant_open.find("assistant") != std::string::npos);
            CHECK(!framing.turn_close.empty());
            CHECK(!framing.generation_open.empty());
        }
    }
    {
        const std::string_view template_text = R"TPL({% for message in messages %}{% if message['role'] == 'system' and message['content'] %}{{'<|system|>
' + message['content'] + '<|end|>
'}}{% elif message['role'] == 'user' %}{{'<|user|>
' + message['content'] + '<|end|>
'}}{% elif message['role'] == 'assistant' %}{{'<|assistant|>
' + message['content'] + '<|end|>
'}}{% endif %}{% endfor %}{% if add_generation_prompt %}{{ '<|assistant|>
' }}{% else %}{{ eos_token }}{% endif %})TPL";
        const ChatFraming framing = compile_chat_framing(template_text);
        CHECK(framing.matched);
        if (framing.matched) {
            const std::string rendered = framing.system_prefix + framing.user_open +
                "Hello" + framing.turn_close + framing.generation_open;
            // Ground truth: jinja2 rendering of the same template with
            // messages=[{"role":"user","content":"Hello"}] and
            // add_generation_prompt=true.
            const std::string expected = R"TPL(<|user|>
Hello<|end|>
<|assistant|>
)TPL";
            CHECK_MSG(rendered == expected, "phi: facts render mismatch");
            CHECK(framing.user_open.find("user") != std::string::npos);
            CHECK(framing.assistant_open.find("assistant") != std::string::npos);
            CHECK(!framing.turn_close.empty());
            CHECK(!framing.generation_open.empty());
        }
    }
    {
        // Reconstructed gemma-3 conversational shape (documented template
        // structure; the model itself is gated, so no byte-exact source).
        const ChatFraming framing = compile_chat_framing(R"TPL({{ bos_token }}
{%- if messages[0]['role'] == 'system' %}{{ messages[0]['content'] }}{%- endif %}
{%- for message in messages %}
    {%- if message['role'] == 'user' %}
        {{- '<start_of_turn>user\n' + message['content'] + '<end_of_turn>\n' }}
    {%- elif message['role'] == 'assistant' %}
        {{- '<start_of_turn>model\n' + message['content'] + '<end_of_turn>\n' }}
    {%- endif %}
{%- endfor %}
{%- if add_generation_prompt %}{{- '<start_of_turn>model\n' }}{%- endif %})TPL");
        CHECK(framing.matched);
        if (framing.matched) {
            CHECK(framing.template_emits_bos);
            CHECK(framing.system_prefix.empty());
            CHECK(framing.user_open == "<start_of_turn>user\n");
            CHECK(framing.assistant_open == "<start_of_turn>model\n");
            CHECK(framing.turn_close == "<end_of_turn>\n");
            CHECK(framing.generation_open == "<start_of_turn>model\n");
            const std::string rendered = framing.user_open + "Hello" +
                framing.turn_close + framing.generation_open;
            CHECK(rendered == "<start_of_turn>user\nHello<end_of_turn>\n<start_of_turn>model\n");
        }
    }
    {
        // Reconstructed llama-3.1 conversational shape (documented template
        // structure).
        const ChatFraming framing = compile_chat_framing(R"TPL({{- bos_token }}
{%- for message in messages %}
    {{- '<|start_header_id|>' + message['role'] + '<|end_header_id|>\n\n' + message['content'] + '<|eot_id|>' }}
{%- endfor %}
{%- if add_generation_prompt %}
    {{- '<|start_header_id|>assistant<|end_header_id|>\n\n' }}
{%- endif %})TPL");
        CHECK(framing.matched);
        if (framing.matched) {
            CHECK(framing.template_emits_bos);
            CHECK(framing.user_open == "<|start_header_id|>user<|end_header_id|>\n\n");
            CHECK(framing.assistant_open ==
                  "<|start_header_id|>assistant<|end_header_id|>\n\n");
            CHECK(framing.turn_close == "<|eot_id|>");
            CHECK(framing.generation_open ==
                  "<|start_header_id|>assistant<|end_header_id|>\n\n");
        }
    }
}

void run_distinct_closers() {
    const auto framing = compile_chat_framing(R"TPL({% for message in messages %}{% if message['role'] == 'user' %}{{ '<u>' + message['content'] + '</u>' }}{% elif message['role'] == 'assistant' %}{{ '<a>' + message['content'] + '</a>' }}{% endif %}{% endfor %}{% if add_generation_prompt %}{{ '<a>' }}{% endif %})TPL");
    CHECK(framing.matched);
    CHECK(framing.assistant_close == "</a>");
    CHECK(framing.user_open + "Hello" + framing.turn_close + framing.generation_open == "<u>Hello</u><a>");
}

void run_unrecognized_templates() {
    {
        const ChatFraming framing = compile_chat_framing(R"TPL()TPL");
        CHECK_MSG(!framing.matched, "unrecognized template must fail closed: empty");
    }
    {
        const ChatFraming framing = compile_chat_framing(R"TPL(just some text)TPL");
        CHECK_MSG(!framing.matched, "unrecognized template must fail closed: non-jinja text");
    }
    {
        const ChatFraming framing = compile_chat_framing(R"TPL({% if tools %}{{ tool }}{% endif %})TPL");
        CHECK_MSG(!framing.matched, "unrecognized template must fail closed: tools-only template");
    }
    {
        const ChatFraming framing = compile_chat_framing(R"TPL({{ custom_var }})TPL");
        CHECK_MSG(!framing.matched, "unrecognized template must fail closed: unknown variable");
    }
    {
        const ChatFraming framing = compile_chat_framing(R"TPL({% if add_generation_prompt %}{{ 'go' }}{% endif %})TPL");
        CHECK_MSG(!framing.matched, "unrecognized template must fail closed: no message loop");
    }
    {
        const ChatFraming framing = compile_chat_framing(R"TPL({% for message in messages %}{{ 'u' + message.content }}{% endfor %})TPL");
        CHECK_MSG(!framing.matched, "unrecognized template must fail closed: loop without generation block");
    }
    {
        const ChatFraming framing = compile_chat_framing(R"TPL(prefix {% if add_generation_prompt %}{{ 'go' }}{% endif %})TPL");
        CHECK_MSG(!framing.matched, "unrecognized template must fail closed: generation block without a loop");
    }
    {
        const ChatFraming framing = compile_chat_framing(R"TPL({% for message in messages %}{{ message.content | trim }}{% endfor %}{% if add_generation_prompt %}{{ 'go' }}{% endif %})TPL");
        CHECK_MSG(!framing.matched, "unrecognized template must fail closed: unsupported loop body");
    }
}

}  // namespace

int main() {
    run_real_templates();
    run_distinct_closers();
    run_unrecognized_templates();
    if (g_failures == 0) {
        std::printf("test_chat_framing: all cases passed\n");
        return 0;
    }
    std::printf("test_chat_framing: %d failures\n", g_failures);
    return 1;
}
